Cloud version of the fix plus integrity checks
crossbordersolutions/snp_data_type_fix pull request #1
Opened 2021-04-26 21:29 UTC by yossi-levi

2021-04-26 22:25 UTC, abernhardxbs commented
lets remove ` .idea/watcherTasks.xml` and make sure it is ignored

2021-04-27 12:48 UTC, KevinBoyette requested changes

2021-04-27 12:48 UTC, KevinBoyette commented on glue/snp_datatype_fix/snp_datatype_fix.py
> +sc = SparkContext()
Just out of curiosity, why do we use SparkContext? I know that was the way to do it in Spark 1.x, but as of Spark 2.x we have SparkSession. I think SparkSession gives you access to the dataframe api as well.  It might not even matter in Glue.

2021-04-27 12:48 UTC, KevinBoyette commented on glue/snp_datatype_fix/snp_datatype_fix.py
> +        df = spark.read.format(source_format).options(**options).load(path)
if options takes an empty dict, what happens? You might be able to combine the if and else statements by always passing in some kind of option.

2021-04-27 12:48 UTC, KevinBoyette commented on glue/snp_datatype_fix/snp_datatype_fix.py
> +    source_df: DataFrame,
all 4 of these params go together all the time it looks like.  Could we pass in a dataclass or a namedtuple?

2021-04-27 13:09 UTC, abernhardxbs commented on glue/snp_datatype_fix/snp_datatype_fix.py
> +sc = SparkContext()
This is something we can look into in the future, but this is meant to address a high priority issue and we should stick to what we are familiar with for it.

2021-04-27 13:09 UTC, abernhardxbs commented on glue/snp_datatype_fix/snp_datatype_fix.py
> +        df = spark.read.format(source_format).options(**options).load(path)
I think the answer to the first question is that it would use the defaults, but something to be tested. As to refactoring the conditional, we can do these sorts of optimizations down the road. Right now, this snippet is clear enough it is more valuable to move to other matters.

2021-04-27 13:09 UTC, abernhardxbs commented on glue/snp_datatype_fix/snp_datatype_fix.py
> +    source_df: DataFrame,
Our testing image is still using python 3.6 because glue v2 is fairly recent and we don't have updated tooling for everything yet. Lets keep it simple for now and come back to this as we refine our code base.

2021-04-27 13:17 UTC, KevinBoyette approved these changes

2021-04-27 13:35 UTC, abernhardxbs approved these changes

2021-04-27 13:37 UTC, yossi-levi commented on glue/snp_datatype_fix/snp_datatype_fix.py
> +    return source_schema.keys() & target_schema.keys()
@abernhardxbs 
I read a bit about it,
The `&` in pyspark is the True\False of 2 values:
https://stackoverflow.com/questions/44508651/pyspark-bitwiseand-vs-ampersand-operator/44508902

I also checked the results of that function and got the right results.

2021-04-27 13:41 UTC, abernhardxbs commented on glue/snp_datatype_fix/snp_datatype_fix.py
> +    return source_schema.keys() & target_schema.keys()
This may be true, but you are using `&` on 2 dictionary `KeysView` objects, not dataframes, this is clearly indicated by your own type hints for the function itself (both `dict` type). It is interesting that it correctly finds the intersection, but it is very unfriendly to read as the expected result is not obvious

https://docs.python.org/3/library/collections.abc.html#collections.abc.KeysView

2021-04-27 18:35 UTC, fguoxbs commented on glue/snp_datatype_fix/snp_datatype_fix.py
> +    return source_schema.keys() & target_schema.keys()
I also have an doubt here about `&`since never use like this before. It seems you want to get the common keys from 2 dicts. Then I searched a bit on this, and saw someone says can just do & in python 3: 
https://stackoverflow.com/questions/1317410/finding-matching-keys-in-two-large-dictionaries-and-doing-it-fast
I tested with 2 simple dicts and it works, but just not sure if this is commonly used.

2021-04-27 18:40 UTC, fguoxbs approved these changes

2021-04-27 18:41 UTC, merged